export interface CheckGuide {
  key: string;
  title: string;
  why: string;
  steps: string[];
  tools?: string[];
  tips?: string[];
}

export const CHECK_GUIDES: Record<string, CheckGuide> = {
  // A. Script setup
  A1: {
    key: "A1",
    title: "Only GTM script in site header",
    why: "Any script hardcoded in the site header fires immediately on page load, bypassing consent entirely. GTM must be the single control plane for all scripts so consent controls apply to everything.",
    steps: [
      "Open the site's CMS admin (Webflow: Site settings > Custom Code > Head Code; HubSpot: Settings > Content > Pages > Site header HTML)",
      "Verify only the GTM container snippet is present (starts with <!-- Google Tag Manager -->)",
      "If other scripts are found (GA4, Meta Pixel, HotJar, etc.), note them as issues - they must be moved into GTM",
      "Check individual page settings too - in Webflow, click each page > gear icon > Head Code",
    ],
    tools: ["Browser DevTools > View Page Source (Ctrl+U / Cmd+Option+U)", "Search for <script in the source"],
    tips: ["The GTM snippet contains a container ID like GTM-XXXXXX - note it for B-category checks"],
  },
  A2: {
    key: "A2",
    title: "No scripts hardcoded in footer",
    why: "Footer scripts also bypass consent. The only exception is the Cookiebot Cookie Declaration script on the cookie policy page, which renders the cookie list (not a tracking script).",
    steps: [
      "Check the site's footer custom code section (Webflow: Site settings > Custom Code > Footer Code)",
      "Check individual page footer code sections",
      "Only the Cookie Declaration script is allowed in the footer, and only on the cookie policy page",
      "Any other scripts (analytics, chat widgets, marketing pixels) must be moved to GTM",
    ],
    tools: ["Browser DevTools > View Page Source", "Search for </body> and check scripts above it"],
  },
  A3: {
    key: "A3",
    title: "Cookiebot CMP tag on correct trigger",
    why: "The Consent Initialization trigger fires before any other trigger in GTM. Using 'All Pages' instead causes tags to fire before consent state is established, resulting in unconsented data collection.",
    steps: [
      "Open Google Tag Manager (tagmanager.google.com)",
      "Find the Cookiebot CMP tag in the Tags list",
      "Click the tag to open its configuration",
      "Check the Triggering section at the bottom",
      "It must say 'Consent Initialization - All Pages' (NOT 'All Pages' or 'Initialization')",
      "If wrong, click the trigger, remove it, and add 'Consent Initialization - All Pages'",
    ],
    tools: ["GTM web interface (tagmanager.google.com)"],
    tips: ["The trigger hierarchy from top to bottom is: Consent Initialization > Initialization > All Pages > DOM Ready > Window Loaded"],
  },
  A4: {
    key: "A4",
    title: "Official Cookiebot GTM template used",
    why: "The official template from the GTM Template Gallery (by Usercentrics) automatically handles Consent Mode V2 integration. Custom HTML tags miss V2 consent fields and don't receive template updates.",
    steps: [
      "Open GTM > Tags > click the Cookiebot CMP tag",
      "Check the tag type - it should say 'Cookiebot CMP' (template icon)",
      "If it says 'Custom HTML', it's wrong - the tag needs to be recreated",
      "To fix: delete the Custom HTML tag, go to Templates > Tag Templates > Search Gallery, search 'Cookiebot CMP', add it, then create a new tag using the template",
    ],
    tools: ["GTM web interface"],
    tips: ["The official template is published by Usercentrics (not Cybot A/S - Cookiebot was acquired by Usercentrics)"],
  },
  A5: {
    key: "A5",
    title: "AutoBlock is OFF",
    why: "AutoBlock is Cookiebot's own script-blocking mechanism. When using Advanced Consent Mode inside GTM, AutoBlock can prevent Google tags from sending cookieless pings - defeating the purpose of Advanced Mode entirely (you lose conversion modeling data). Consent-aware tags manage their own blocking, so AutoBlock is redundant and potentially harmful. Turning it off is the simpler, recommended approach.",
    steps: [
      "Open GTM > Tags > click the Cookiebot CMP tag",
      "Look for the AutoBlock setting in the tag configuration",
      "Verify it is set to OFF",
      "If AutoBlock must stay ON (client requirement), ensure GTM and CMP scripts have data-cookieconsent=\"ignore\" attribute to prevent them from being accidentally blocked",
    ],
    tools: ["GTM web interface"],
    tips: ["AutoBlock CAN work alongside GTM if properly configured, but OFF is simpler and less error-prone"],
  },

  // B. GTM configuration
  B1: {
    key: "B1",
    title: "All tracking scripts inside GTM",
    why: "Scripts running outside GTM bypass the consent management system entirely. GTM must be the single point of control for all tracking.",
    steps: [
      "Open the site in Chrome with DevTools > Network tab",
      "Reload the page and watch network requests",
      "Filter by 'JS' to see script loads",
      "Look for known tracking domains loading outside GTM: google-analytics.com, connect.facebook.net, snap.licdn.com, static.hotjar.com",
      "Cross-reference with GTM - every tracking script should have a corresponding tag in GTM",
      "Also check the page source for inline tracking scripts",
    ],
    tools: ["Chrome DevTools > Network tab", "GTM Preview Mode (Tag Assistant)"],
    tips: ["The GTM snippet itself (gtm.js) is the only tracking-related script that should load outside GTM"],
  },
  B2: {
    key: "B2",
    title: "Google tags: consent overview set",
    why: "Google tags (GA4, Google Ads, Floodlight) support Advanced Consent Mode natively. They self-adapt to the consent state, sending cookieless pings when consent is denied. Setting 'No additional consent required' lets them function in this mode.",
    steps: [
      "Open GTM > Tags list",
      "Click the shield icon (Consent Overview) at the top of the Tags list",
      "Find all Google tags (GA4 Configuration, Google Ads Conversion, Google Ads Remarketing, Floodlight)",
      "Each should show 'No additional consent required'",
      "If any show 'Not set', click to configure and select 'No additional consent required'",
    ],
    tools: ["GTM web interface > Consent Overview"],
  },
  B3: {
    key: "B3",
    title: "Non-Google tags: consent gated",
    why: "Non-Google tags (Meta Pixel, LinkedIn, HotJar, etc.) don't support Consent Mode. They must be completely blocked until the user grants consent, otherwise they fire and set cookies without permission.",
    steps: [
      "Open GTM > Consent Overview (shield icon)",
      "Find all non-Google tags",
      "Each must show 'Require additional consent'",
      "Click each to verify the correct consent type is set:",
      "  - Marketing/ad tags (Meta, LinkedIn, TikTok): ad_storage",
      "  - Analytics tags (HotJar, Clarity): analytics_storage",
      "  - Tags serving both purposes: both ad_storage and analytics_storage",
    ],
    tools: ["GTM web interface > Consent Overview"],
    tips: [
      "Common mapping: Meta Pixel = ad_storage, LinkedIn Insight = ad_storage, HotJar = analytics_storage, Microsoft Clarity = analytics_storage",
    ],
  },
  B4: {
    key: "B4",
    title: "Non-Google tag triggers correct",
    why: "Non-Google tags must use the cookie_consent_update trigger, not 'All Pages'. The cookie_consent_update event fires only after the user makes a consent choice, ensuring these tags only run with explicit permission.",
    steps: [
      "Open GTM > Tags list",
      "Click each non-Google tag",
      "Check the Triggering section",
      "The trigger must be 'cookie_consent_update' (custom event), NOT 'All Pages'",
      "Also check that tag firing is set to 'Once per page' to prevent duplicate firing if the user changes consent",
    ],
    tools: ["GTM web interface"],
    tips: ["If the cookie_consent_update trigger doesn't exist, create it: Triggers > New > Custom Event > Event name: cookie_consent_update"],
  },
  B5: {
    key: "B5",
    title: "Google Consent Mode V2 enabled",
    why: "Mandatory since March 2024 under the Digital Markets Act (DMA). Without V2, Google services will not process EEA user data. V2 adds ad_user_data and ad_personalization parameters.",
    steps: [
      "Open GTM Preview Mode (Tag Assistant) on the site",
      "Click the 'Consent Initialization' event in the left panel",
      "Go to the Consent tab",
      "Verify all 7 parameters are present: ad_storage, ad_user_data, ad_personalization, analytics_storage, functionality_storage, personalization_storage, security_storage",
      "Before user interaction, all should show 'Denied' (except security_storage which is 'Granted')",
      "Click Accept All on the banner, then check again - all should show 'Granted'",
    ],
    tools: ["GTM Preview Mode (tagassistant.google.com)", "MeasureMinds Consent Mode Monitor (Chrome extension)"],
    tips: ["The V2-specific parameters are ad_user_data and ad_personalization. If these two are missing but the other 5 are present, you have V1 only, which is non-compliant since March 2024."],
  },

  // C. Cookie categories
  C1: {
    key: "C1",
    title: "Necessary cookies identified",
    why: "Necessary cookies (session, security, CDN) don't require consent but must still be documented. Misclassifying a tracking cookie as 'necessary' is a common GDPR violation.",
    steps: [
      "Open admin.cookiebot.com > select the domain",
      "Go to the cookie list / last scan results",
      "Check the 'Necessary' category",
      "Verify each cookie listed as necessary is truly essential: CDN cookies (Webflow, Cloudflare), session cookies, CSRF tokens, load balancer cookies",
      "Flag any analytics or marketing cookies incorrectly classified as necessary",
    ],
    tools: ["Cookiebot admin (admin.cookiebot.com)", "Chrome DevTools > Application > Cookies"],
  },
  C2: {
    key: "C2",
    title: "Statistics cookies under consent",
    why: "Analytics cookies (GA4, HotJar, etc.) collect user behavior data and require explicit opt-in consent in the EU/EEA.",
    steps: [
      "In Cookiebot admin, check the 'Statistics' category",
      "Verify GA4 cookies are listed: _ga, _ga_*, _gid",
      "Verify other analytics cookies if applicable: _hjSessionUser_*, _hjSession_* (HotJar), _clsk, _clck (Clarity)",
      "Test: decline all cookies on the site, then check DevTools > Application > Cookies - no analytics cookies should be present",
    ],
    tools: ["Cookiebot admin", "Chrome DevTools > Application > Cookies"],
  },
  C3: {
    key: "C3",
    title: "Marketing cookies under consent",
    why: "Marketing/advertising cookies track users across sites for ad targeting. They require explicit consent and are often the highest-risk category for GDPR violations.",
    steps: [
      "In Cookiebot admin, check the 'Marketing' category",
      "Verify ad platform cookies are listed: _fbp (Meta), _gcl_au (Google Ads), li_fat_id (LinkedIn), _ttp (TikTok)",
      "Test: accept only Statistics on the banner, then check DevTools > Cookies - no marketing cookies should appear",
      "Test: accept all, then verify marketing cookies do appear",
    ],
    tools: ["Cookiebot admin", "Chrome DevTools > Application > Cookies"],
  },
  C4: {
    key: "C4",
    title: "Preference cookies under consent",
    why: "Preference cookies store user choices like language or UI settings. While less risky than marketing cookies, they still require consent if they're not strictly necessary for the site to function.",
    steps: [
      "In Cookiebot admin, check the 'Preferences' category",
      "Common preference cookies: language selection, dark/light mode, font size",
      "If the site doesn't use preference cookies, mark this check as N/A",
      "If present, verify they're correctly categorized and only set after consent",
    ],
    tools: ["Cookiebot admin"],
    tips: ["Many sites don't have preference cookies - this check is often N/A"],
  },
  C5: {
    key: "C5",
    title: "No unclassified cookies",
    why: "Unclassified cookies haven't been reviewed and categorized. They could be tracking cookies firing without proper consent. All cookies must be categorized in Cookiebot.",
    steps: [
      "Open admin.cookiebot.com > select the domain",
      "Run a new scan if the last scan is older than 1 week",
      "Check for any 'Unclassified' cookies in the results",
      "For each unclassified cookie: identify its source, determine the correct category, and classify it in Cookiebot admin",
    ],
    tools: ["Cookiebot admin > Scan results"],
    tips: ["New cookies can appear when scripts are updated or new integrations are added - scan regularly"],
  },

  // D. Legacy/cleanup
  D1: {
    key: "D1",
    title: "No ghost scripts",
    why: "Discontinued services often leave behind scripts that still load and set cookies. These are invisible compliance risks - they track users without anyone at the company knowing.",
    steps: [
      "Open the site with DevTools > Network tab",
      "Look for requests to domains of services the client no longer uses",
      "Common ghost scripts: HotJar (if subscription expired), Leadfeeder, old chat widgets (Drift, Intercom), old A/B testing tools",
      "Check GTM for tags that reference discontinued services",
      "Ask the client: 'Do you still use [service]?' for any unfamiliar scripts",
    ],
    tools: ["Chrome DevTools > Network tab", "GTM tag list"],
  },
  D2: {
    key: "D2",
    title: "No old campaign scripts",
    why: "Marketing campaigns often add temporary tracking scripts that never get removed. These continue to fire and send data to platforms the client may no longer use.",
    steps: [
      "Check GTM for tags related to specific campaigns (often named with dates or campaign names)",
      "Check the site source for inline campaign tracking (common on landing pages and thank-you pages)",
      "Look for Salesforce, Pardot, or marketing automation scripts that may be from old campaigns",
      "Before removing: confirm with the client that the campaign is inactive",
    ],
    tools: ["GTM tag list", "View page source on landing pages"],
    tips: ["Don't remove campaign scripts without client confirmation - some campaigns run longer than expected"],
  },
  D3: {
    key: "D3",
    title: "No orphaned pixels",
    why: "Pixels placed directly in the site header instead of GTM bypass consent controls. They were often added before GTM was set up and forgotten.",
    steps: [
      "View page source (Ctrl+U / Cmd+Option+U)",
      "Search for common pixel patterns: fbq( (Meta), lintrk( (LinkedIn), ttq( (TikTok), hj( (HotJar)",
      "Search for tracking pixel image tags: <img with domains like facebook.com, linkedin.com, doubleclick.net",
      "If found: these need to be removed from the site code and managed through GTM instead",
    ],
    tools: ["View page source", "Search for pixel-related code patterns"],
  },

  // E. Third-party services
  E1: {
    key: "E1",
    title: "Video embeds audited",
    why: "YouTube and Vimeo embeds load cookies and transfer user data on page load, before any consent. They must be blocked until consent or use privacy-enhanced modes.",
    steps: [
      "Search the site for embedded videos (YouTube, Vimeo, Wistia)",
      "For YouTube: verify the embed URL uses youtube-nocookie.com (NOT youtube.com or youtu.be)",
      "Check that video iframes use data-src instead of src (Cookiebot swaps data-src to src after consent)",
      "Check for data-cookieconsent=\"marketing\" attribute on the iframe",
      "Test: decline cookies, then try to play an embedded video - it should show a consent placeholder, not play",
    ],
    tools: ["View page source", "Search for iframe and youtube/vimeo"],
    tips: ["In Webflow, use an Embed element with raw HTML instead of the native video component to add custom attributes"],
  },
  E2: {
    key: "E2",
    title: "Google Fonts self-hosted",
    why: "Google Fonts loaded from fonts.googleapis.com transfers the visitor's IP address to Google on every page load. A Munich court set a precedent of EUR 100 per violation. Self-hosting eliminates this risk entirely.",
    steps: [
      "Open the site with DevTools > Network tab",
      "Filter for 'fonts.googleapis.com' and 'fonts.gstatic.com'",
      "If any requests appear, Google Fonts is loaded from the CDN - this is an issue",
      "To fix in Webflow: download fonts from Google Fonts or google-webfonts-helper, upload to Webflow Assets, configure as Custom Fonts in Project Settings",
      "After fixing, reload and verify no requests to Google font domains",
    ],
    tools: ["Chrome DevTools > Network tab", "Filter: fonts.googleapis.com"],
    tips: ["google-webfonts-helper (gwfh.mranftl.com/fonts) makes downloading and self-hosting easy"],
  },
  E3: {
    key: "E3",
    title: "Maps blocked until consent",
    why: "Google Maps and other map services load scripts and set cookies. They must be blocked until consent or replaced with static images that link to the map service.",
    steps: [
      "Search the site for embedded maps (Google Maps, Mapbox, OpenStreetMap)",
      "If Google Maps iframe is found: check for data-cookieconsent and data-src attributes (same pattern as video embeds)",
      "Alternative: replace the interactive map with a static screenshot image that links to Google Maps",
      "Test: decline cookies, verify the map doesn't load (shows consent placeholder or static image instead)",
    ],
    tools: ["View page source", "Search for maps.google or mapbox"],
    tips: ["A static map image with a 'View on Google Maps' link is the simplest compliant solution"],
  },
  E4: {
    key: "E4",
    title: "Chat widgets checked",
    why: "Chat widgets (Intercom, Drift, Zendesk, Crisp, etc.) often set cookies for session tracking and analytics. If they set non-essential cookies, they need consent before loading.",
    steps: [
      "Check if the site has a chat widget (usually bottom-right corner)",
      "Identify the provider and check what cookies it sets",
      "If the widget sets non-essential cookies: it must be loaded through GTM with consent gating",
      "If the widget only uses session cookies essential for the chat function: it may be classified as necessary",
      "Check Cookiebot's cookie report for chat-related cookies",
    ],
    tools: ["Cookiebot admin > cookie list", "Chrome DevTools > Application > Cookies"],
    tips: ["If no chat widget exists on the site, mark as N/A"],
  },
  E5: {
    key: "E5",
    title: "Social embeds checked",
    why: "Social media embeds (Twitter/X feeds, Instagram posts, Facebook Like buttons, share buttons) load third-party scripts and cookies. They track users even if they don't interact with the embed.",
    steps: [
      "Search the site for social media embeds: Twitter feeds, Instagram galleries, Facebook Like/Share buttons, LinkedIn badges",
      "Check if they load third-party scripts (platform.twitter.com, connect.facebook.net, etc.)",
      "If present: they should be loaded through GTM with consent gating, or use click-to-load placeholders",
      "Simple share links (plain URLs without embedded scripts) are fine - no consent needed",
    ],
    tools: ["View page source", "Chrome DevTools > Network tab"],
    tips: ["If the site only has simple share links (no embedded scripts), mark as N/A"],
  },
  E6: {
    key: "E6",
    title: "CRM integrations reviewed",
    why: "CRM platforms (HubSpot, Salesforce) process personal data. A Data Processing Agreement (DPA) must be in place, and the data transfer mechanism must be verified (especially for US-based services).",
    steps: [
      "Identify all CRM integrations on the site",
      "For each CRM: verify a DPA is signed between the client and the CRM provider",
      "For US-based CRMs: check if the provider is DPF-certified (dataprivacyframework.gov)",
      "Check if CRM tracking scripts are managed through GTM with proper consent",
      "Review what data is sent to the CRM (form submissions, page views, user behavior)",
    ],
    tools: ["Client's CRM admin", "dataprivacyframework.gov"],
    tips: ["Most major CRMs (HubSpot, Salesforce) have standard DPAs available in their settings or legal pages"],
  },

  // F. Forms & data collection
  F1: {
    key: "F1",
    title: "All forms identified",
    why: "Every form on the site collects personal data. You can't audit what you haven't found. A complete inventory prevents overlooked compliance gaps.",
    steps: [
      "Browse every page of the site systematically",
      "Document each form found: contact forms, newsletter signups, login/register forms, search forms, quote request forms",
      "Check for forms in modals/popups that may not be visible on initial page load",
      "Check for forms on subdomains or microsites",
      "Note what data each form collects (name, email, phone, company, message, etc.)",
    ],
    tools: ["Manual site review", "Sitemap for page list"],
  },
  F2: {
    key: "F2",
    title: "Data minimization",
    why: "GDPR Article 5(1)(c) requires collecting only data that is adequate, relevant, and limited to what is necessary. A contact form asking for date of birth is likely excessive.",
    steps: [
      "For each form identified in F1, review the fields",
      "Ask: is each field necessary for the stated purpose?",
      "Contact form: name + email + message is typically sufficient. Phone number may be optional.",
      "Newsletter signup: email only (name is nice-to-have but not necessary)",
      "Flag any fields that seem excessive for the form's purpose",
    ],
    tips: ["Optional fields are fine as long as they're clearly marked optional - the issue is requiring data that isn't needed"],
  },
  F3: {
    key: "F3",
    title: "Privacy policy linked at/near form",
    why: "GDPR requires informing users about data processing at the point of collection (Articles 13/14). A link to the privacy policy near the form fulfills this requirement.",
    steps: [
      "Check each form for a privacy policy link",
      "The link should be visible near the form (below the submit button or near the consent checkbox)",
      "Verify the link works and goes to the actual privacy policy page",
      "The text can be simple: 'By submitting this form, you agree to our Privacy Policy' with Privacy Policy as a link",
    ],
  },
  F4: {
    key: "F4",
    title: "Separate consent per purpose",
    why: "Consent must be specific to each purpose (GDPR Article 6). A single checkbox covering both 'respond to your inquiry' and 'send you marketing emails' is not valid - these are separate purposes requiring separate consent.",
    steps: [
      "Check each form for consent checkboxes",
      "If the form serves multiple purposes (e.g., contact + newsletter), there must be separate checkboxes",
      "Verify no checkboxes are pre-ticked (consent must be actively given)",
      "The inquiry/contact purpose may not need a checkbox (legitimate interest or contract performance), but marketing always requires explicit opt-in",
    ],
    tips: ["A contact form that only handles inquiries may not need a consent checkbox - the legal basis is contract performance or legitimate interest. But a newsletter signup checkbox on that same form requires separate, explicit consent."],
  },
  F5: {
    key: "F5",
    title: "Form submissions encrypted",
    why: "Personal data submitted through forms must be transmitted securely. Unencrypted form submissions (HTTP instead of HTTPS) expose personal data in transit.",
    steps: [
      "Check that the site uses HTTPS (padlock icon in browser address bar)",
      "Verify the form action URL uses HTTPS (not HTTP)",
      "Check that there are no mixed content warnings in DevTools console",
      "If the form submits to a third-party service, verify that service also uses HTTPS",
    ],
    tools: ["Browser address bar (padlock)", "Chrome DevTools > Console (mixed content warnings)"],
    tips: ["Almost all modern sites use HTTPS. This check is mainly relevant for older sites or custom form handlers."],
  },

  // G. Consent banner
  G1: {
    key: "G1",
    title: "Banner appears on first visit",
    why: "The consent banner must be shown before any non-essential cookies are set. If it doesn't appear, cookies may be set without consent.",
    steps: [
      "Open the site in a fresh incognito/private window",
      "The consent banner should appear immediately on page load",
      "If it doesn't appear: check if Cookiebot is properly configured, check for JavaScript errors in DevTools console",
      "Also test on mobile - the banner must be visible and functional on all screen sizes",
    ],
    tools: ["Incognito window", "Mobile device or responsive mode in DevTools"],
  },
  G2: {
    key: "G2",
    title: "Accept and Reject equally prominent",
    why: "EDPB guidelines require that refusing consent must be as easy as giving it. Making 'Accept' a big green button and 'Reject' a tiny gray link is a dark pattern and non-compliant.",
    steps: [
      "Open the consent banner in a fresh incognito window",
      "Compare the Accept and Reject buttons",
      "They should be the same size, same visual weight (color contrast), and require the same number of clicks",
      "A common violation: Accept is a button, Reject is a text link hidden in the banner",
      "Another violation: Accept is on the first screen, but Reject requires opening 'Settings' first",
    ],
    tips: ["The safest approach is two identical buttons side by side: 'Accept All' and 'Reject All'"],
  },
  G3: {
    key: "G3",
    title: "Granular category controls available",
    why: "Users must be able to choose which cookie categories to accept (e.g., accept analytics but reject marketing). An all-or-nothing choice is not sufficient under GDPR.",
    steps: [
      "Open the consent banner",
      "Look for a 'Customize' or 'Manage preferences' option",
      "Verify it shows individual categories: Necessary, Preferences, Statistics, Marketing",
      "Verify each non-necessary category has a toggle/checkbox that can be independently controlled",
      "The Necessary category should be always-on and not toggleable",
    ],
  },
  G4: {
    key: "G4",
    title: "Declining actually blocks scripts",
    why: "The banner is meaningless if scripts fire regardless of the user's choice. This is the most critical functional test - consent must actually control script behavior.",
    steps: [
      "Open a fresh incognito window with DevTools > Network tab open",
      "When the banner appears, click Decline/Reject All",
      "Check the Network tab for tracking requests after declining",
      "Check DevTools > Application > Cookies - only the CookieConsent cookie should be present",
      "No _ga, _fbp, _gcl_au, or other tracking cookies should exist",
      "If tracking requests or cookies appear after declining, this is a critical compliance failure",
    ],
    tools: ["Chrome DevTools > Network tab", "Chrome DevTools > Application > Cookies"],
  },
  G5: {
    key: "G5",
    title: "Consent remembered on return",
    why: "The consent choice must persist. Showing the banner on every visit is both annoying and potentially non-compliant (it pressures users to change their mind).",
    steps: [
      "Open the site in a normal (non-incognito) window",
      "Make a consent choice (accept or decline)",
      "Close the tab and reopen the site",
      "The banner should NOT reappear - the previous choice should be remembered",
      "Check DevTools > Application > Cookies for the CookieConsent cookie - it should persist",
    ],
    tools: ["Chrome DevTools > Application > Cookies"],
    tips: ["The CookieConsent cookie typically has a 12-month expiry. After that, the banner reappears for re-consent."],
  },
  G6: {
    key: "G6",
    title: "Banner in correct language(s)",
    why: "The consent banner must be in the language(s) the site uses. A Swedish site showing an English-only banner fails the informed consent requirement.",
    steps: [
      "Check what language(s) the site content is in",
      "Verify the consent banner matches the site language",
      "For multi-language sites: switch languages and verify the banner updates accordingly",
      "In Cookiebot admin: check that the correct languages are configured under Settings > Languages",
    ],
    tools: ["Cookiebot admin > Settings > Languages"],
  },
  G7: {
    key: "G7",
    title: "No dark patterns",
    why: "Dark patterns in consent interfaces are explicitly prohibited by EDPB guidelines and increasingly enforced by DPAs. Fines for dark patterns in consent are growing.",
    steps: [
      "Review the banner for these dark patterns:",
      "  - Pre-ticked consent boxes (must be unticked by default)",
      "  - Cookie walls (blocking site access unless consent is given)",
      "  - Guilt language ('We use cookies to give you the best experience' implying you must accept)",
      "  - Hidden reject option (Reject is a tiny link, Accept is a big button)",
      "  - Confusing language (double negatives, unclear what each option does)",
      "  - Forced repeated prompting (banner reappears after declining)",
    ],
    tips: ["Compare to the EDPB Dark Patterns Guidelines (adopted January 2023) for a complete list"],
  },

  // H. Verification
  H1: {
    key: "H1",
    title: "Cookiebot compliance scan run",
    why: "Cookiebot's scanner crawls the site and finds all cookies, scripts, and trackers. The scan results are the source of truth for what cookies exist and whether they're classified.",
    steps: [
      "Log into admin.cookiebot.com",
      "Select the domain",
      "Click 'Scan' or check when the last scan was run",
      "If the last scan is older than 1 week, run a new scan",
      "Review the results: check for unclassified cookies, new cookies, or cookies that have changed",
      "Document the scan date and result",
    ],
    tools: ["Cookiebot admin (admin.cookiebot.com)"],
  },
  H2: {
    key: "H2",
    title: "Cookiebot GCM Check run",
    why: "The Google Consent Mode (GCM) Checker in Cookiebot verifies that Consent Mode V2 is properly integrated. It checks parameter transmission and correct behavior.",
    steps: [
      "Log into admin.cookiebot.com",
      "Select the domain",
      "Find and click 'Start GCM Check' (Google Consent Mode Check)",
      "Review the results - it should confirm that all V2 parameters are properly transmitting",
      "Document the check date and result",
    ],
    tools: ["Cookiebot admin > GCM Check"],
  },
  H3: {
    key: "H3",
    title: "GTM Preview Mode test: decline all",
    why: "This is the definitive test that consent denial actually works. GTM Preview Mode shows exactly which tags fired and which didn't, and the consent state at each point.",
    steps: [
      "Open GTM > Preview (connects Tag Assistant at tagassistant.google.com)",
      "Enter the site URL and click Connect",
      "In a new incognito window, the site opens with GTM Preview connected",
      "Click the 'Consent Initialization' event in Tag Assistant",
      "Go to Consent tab - all parameters should show 'Denied' (except security_storage)",
      "Click Decline/Reject All on the consent banner",
      "Check the 'Tags' tab - non-Google tags should appear under 'Tags Not Fired'",
      "Google tags may still appear under 'Tags Fired' (Advanced Consent Mode - they send cookieless pings)",
    ],
    tools: ["GTM Preview Mode (tagassistant.google.com)"],
  },
  H4: {
    key: "H4",
    title: "GTM Preview Mode test: accept all",
    why: "Verifies that all tags fire correctly when full consent is granted. If tags don't fire after acceptance, the consent configuration has errors.",
    steps: [
      "Open GTM Preview Mode on the site (fresh incognito window)",
      "Click Accept All on the consent banner",
      "In Tag Assistant, check the Consent tab - all parameters should show 'Granted'",
      "Check the Tags tab - ALL tags (Google and non-Google) should appear under 'Tags Fired'",
      "If any tags are under 'Tags Not Fired' after acceptance, their consent configuration or trigger is wrong",
    ],
    tools: ["GTM Preview Mode"],
  },
  H5: {
    key: "H5",
    title: "GTM Preview Mode test: selective",
    why: "Tests that granular consent works correctly. Accepting only statistics should fire analytics tags but NOT marketing tags.",
    steps: [
      "Open GTM Preview Mode on the site (fresh incognito window)",
      "Open the consent banner's granular controls (Customize/Manage preferences)",
      "Accept only Statistics, decline Marketing",
      "In Tag Assistant, check which tags fired:",
      "  - Analytics tags (GA4, HotJar): should be under 'Tags Fired'",
      "  - Marketing tags (Meta Pixel, LinkedIn): should be under 'Tags Not Fired'",
      "Check cookies in DevTools: analytics cookies (_ga) present, marketing cookies (_fbp) absent",
    ],
    tools: ["GTM Preview Mode", "Chrome DevTools > Application > Cookies"],
  },
  H6: {
    key: "H6",
    title: "Cookie tab check in DevTools",
    why: "The ultimate verification - directly checking what cookies exist in the browser. This catches any cookies that slip through regardless of GTM configuration.",
    steps: [
      "Open a fresh incognito window with DevTools > Application > Cookies",
      "Before interacting with the consent banner:",
      "  - Only CookieConsent cookie should exist (and possibly necessary cookies)",
      "  - No _ga, _fbp, _gcl_au, _hjSession, or other tracking cookies",
      "Click Decline All:",
      "  - Still only CookieConsent + necessary cookies",
      "  - Refresh the page and check again - no tracking cookies should appear",
      "Open a new incognito window, Accept All:",
      "  - Tracking cookies should now appear (_ga, _fbp, etc.)",
    ],
    tools: ["Chrome DevTools > Application > Cookies"],
  },

  // I. Privacy documentation
  I1: {
    key: "I1",
    title: "Privacy Policy complete (Art. 13/14)",
    why: "GDPR Articles 13 and 14 list specific information that must be provided to data subjects. Missing any required element makes the privacy policy non-compliant.",
    steps: [
      "Open the site's privacy policy page",
      "Check for each required element:",
      "  - Identity and contact details of the controller (company name, address, email)",
      "  - DPO contact details (if applicable)",
      "  - Purposes of processing and legal basis for each",
      "  - Categories of personal data processed",
      "  - Recipients or categories of recipients",
      "  - International transfers and safeguards (DPF, SCCs)",
      "  - Retention periods for each category of data",
      "  - Data subject rights (access, rectification, erasure, portability, objection)",
      "  - Right to withdraw consent",
      "  - Right to lodge a complaint with a supervisory authority",
      "  - Whether providing data is a statutory/contractual requirement",
    ],
  },
  I2: {
    key: "I2",
    title: "Privacy Policy in site language(s)",
    why: "The privacy policy must be in a language the user understands. A Swedish site with an English-only privacy policy doesn't properly inform Swedish-speaking users.",
    steps: [
      "Identify all languages the site content is available in",
      "Check if the privacy policy exists in each of those languages",
      "For multi-language sites: switch languages and verify the privacy policy link leads to the correct language version",
    ],
  },
  I3: {
    key: "I3",
    title: "Cookie Policy exists (separate page)",
    why: "The cookie policy provides detailed information about each cookie: name, purpose, duration, and vendor. The Cookiebot Cookie Declaration script auto-generates this from scan data.",
    steps: [
      "Check if the site has a separate cookie policy page (distinct from the privacy policy)",
      "Verify the Cookiebot Cookie Declaration is embedded on this page",
      "The declaration should show: cookie name, provider, purpose, expiry, and type for each cookie",
      "Verify the declaration data is current (matches the last Cookiebot scan)",
    ],
    tools: ["Manual check of the cookie policy page"],
    tips: ["The Cookie Declaration is embedded with a script tag - check the page source for CookieDeclaration"],
  },
  I4: {
    key: "I4",
    title: "Privacy Policy linked from every page",
    why: "Users must be able to access the privacy policy from any page on the site. A footer link is the standard approach.",
    steps: [
      "Check the site footer for a privacy policy link",
      "Click the link and verify it goes to the actual privacy policy",
      "Browse several pages and confirm the footer link is present on all of them",
      "Also check for a cookie policy link in the footer",
    ],
  },
  I5: {
    key: "I5",
    title: "Script inventory documented",
    why: "An internal record of all scripts running on the site, their purposes, and their data processing activities. This is essential for accountability and for keeping the consent configuration up to date.",
    steps: [
      "Check if there's an internal document listing all scripts/services on the site",
      "The inventory should include: script name, vendor, purpose, what data it collects, cookie category, DPA status",
      "Cross-reference with the GTM tag list and Cookiebot scan results",
      "If no inventory exists, this is an issue - create one from the GTM tag list and Cookiebot scan",
    ],
    tips: ["The script inventory is an internal document, not published on the site. It supports accountability (GDPR Art. 5(2))."],
  },

  // J. Data processing & legal
  J1: {
    key: "J1",
    title: "DPAs in place for all processors",
    why: "GDPR Article 28 requires a written contract (DPA) with every entity that processes personal data on your behalf. Processing without a DPA is a direct violation.",
    steps: [
      "List all third-party services that process personal data: analytics (Google), CRM (HubSpot), email (Mailchimp), hosting (Webflow), CDN (Cloudflare), payment processors",
      "For each service: check if a DPA is signed",
      "Most major services have standard DPAs in their settings or legal pages",
      "Document the DPA status for each vendor",
    ],
    tips: [
      "Google: Admin console > Account > Legal",
      "HubSpot: Settings > Account > Data Privacy",
      "Webflow: automatically covered in their Terms of Service",
    ],
  },
  J2: {
    key: "J2",
    title: "Vendor inventory maintained",
    why: "A vendor inventory is part of the Records of Processing Activities (ROPA) required by GDPR Article 30. It tracks who processes what data and under what terms.",
    steps: [
      "Check if a vendor/processor inventory document exists",
      "It should list: vendor name, what data they process, processing purpose, DPA status, data transfer mechanism, last review date",
      "Cross-reference with the script inventory (I5) and Cookiebot scan results",
      "If no inventory exists, create one",
    ],
  },
  J3: {
    key: "J3",
    title: "US services DPF-certified",
    why: "The EU-US Data Privacy Framework (DPF) is the current legal mechanism for transferring personal data from the EU to the US. US service providers must be DPF-certified for the transfer to be lawful.",
    steps: [
      "List all US-based services used on the site (Google, Meta, HubSpot, etc.)",
      "For each: go to dataprivacyframework.gov and search for the company",
      "Verify the certification is active (not expired or withdrawn)",
      "If a US service is NOT DPF-certified, alternative transfer mechanisms are needed (SCCs)",
      "Document the DPF certification status for each US vendor",
    ],
    tools: ["dataprivacyframework.gov"],
  },
  J4: {
    key: "J4",
    title: "Data subject rights process exists",
    why: "GDPR gives individuals rights to access, rectify, erase, and port their data. The organization must have a process to handle these requests within 30 days.",
    steps: [
      "Ask the client: do you have a process for handling data subject access requests (DSARs)?",
      "Check if there's a documented procedure: who receives requests, how they're tracked, who fulfills them, response templates",
      "Check the privacy policy - it should explain how users can exercise their rights",
      "Verify there's a contact method for data rights requests (email, form, or DPO contact)",
    ],
    tips: ["This check may result in N/A if the audit scope is limited to the website only. But note it as a recommendation."],
  },
  J5: {
    key: "J5",
    title: "Data breach response plan exists",
    why: "GDPR Article 33 requires notifying the supervisory authority within 72 hours of becoming aware of a personal data breach. Without a plan, the 72-hour clock will be missed.",
    steps: [
      "Ask the client: do you have a data breach response plan?",
      "The plan should include: who to notify internally, assessment procedure, supervisory authority notification template, data subject notification template, breach register",
      "Check if the plan includes the 72-hour notification requirement",
      "If no plan exists, flag as an issue and recommend creating one",
    ],
    tips: ["Like J4, this may be outside the website audit scope but should be flagged as a recommendation"],
  },

  // K. Geo-targeting
  K1: {
    key: "K1",
    title: "EU/EEA visitors get opt-in banner",
    why: "EU/EEA visitors require the strictest consent model: opt-in with all non-essential cookies blocked until explicit consent is given.",
    steps: [
      "Check Cookiebot admin > Settings > Geo-targeting",
      "Verify EU/EEA is configured with the opt-in consent model",
      "Test with a VPN or browser extension set to an EU country",
      "The banner should show full blocking consent: Accept All, Reject All, and Customize options",
      "After declining, no non-essential cookies should be set",
    ],
    tools: ["Cookiebot admin > Geo-targeting", "VPN for location testing"],
    tips: ["If geo-targeting is not configured, the safe default is to apply EU opt-in rules globally"],
  },
  K2: {
    key: "K2",
    title: "US visitors get appropriate notice",
    why: "US privacy laws (CCPA/CPRA in California, state laws in Virginia, Colorado, etc.) use an opt-out model. Visitors must be informed and given the ability to opt out, but blocking by default is not required.",
    steps: [
      "Check Cookiebot admin > Geo-targeting for US region configuration",
      "If California traffic exists: check for a 'Do Not Sell or Share My Personal Information' link",
      "Check that the Global Privacy Control (GPC) browser signal is honored",
      "Test with a VPN set to a US location - the banner should show a notice/opt-out model, not full blocking",
    ],
    tools: ["Cookiebot admin > Geo-targeting", "VPN for location testing"],
    tips: ["If the site has minimal US traffic, this check may be N/A. But if it targets US audiences, it's important."],
  },
  K3: {
    key: "K3",
    title: "UK visitors handled correctly",
    why: "Post-Brexit, the UK has its own data protection regime. After the Data Use and Access Act (DUAA, Feb 2026), UK rules diverge from EU: marketing cookies still require consent, but analytics can load without consent.",
    steps: [
      "Check Cookiebot admin > Geo-targeting for UK region configuration",
      "UK model (post-DUAA Feb 2026): marketing cookies require opt-in consent, analytics cookies can load without consent",
      "If the site targets UK visitors, verify the geo-targeting reflects this distinction",
      "Test with a VPN set to the UK",
    ],
    tools: ["Cookiebot admin > Geo-targeting", "VPN for location testing"],
    tips: [
      "If the site has no UK-specific audience, EU rules (stricter) apply and this can be marked N/A",
      "The DUAA analytics exemption depends on implementing regulations still being finalized. Until published, applying EU opt-in rules to UK visitors is the safer approach. Check ICO guidance for updates.",
    ],
  },
};
